### ISSUE TITLE
Repeatedly resending the same clips

### ISSUE THREAD

**Issue by azpha** [txj-xyz/medal-tv-discord-webhook#2] opened 2022-02-03 04:46 UTC
The webbook is spammed with the same clips over and over again. It doesn't do this when it's first started, but as soon as another clip is uploaded it will be thrown into a loop.
It doesn't seem like there's any checks against this happening, other than ensuring the first clip fetched when the app is started isn't sent again

![image](https://user-images.githubusercontent.com/68027680/152281768-7477026d-c0e4-40d7-bd5c-6dd0064ad797.png)

**Comment by txj-xyz** [comment] 2022-02-03 07:56
Oops, ill fix that tomorrow :)

**Comment by txj-xyz** [comment] 2022-02-03 14:45
@awexthedev I uploaded 2 clips and it looks fine to me after waiting a few minutes after each clip. 

Could you elaborate?

![](https://cdn.discordapp.com/attachments/918670717753630822/938807213500301362/oRQLArFf9m9E6O9LC9pn.png)

**Comment by txj-xyz** [comment] 2022-02-03 14:49
The checks themselves are defined here

Initial clip ID
https://github.com/txj-xyz/medal-tv-discord-webhook/blob/54c697e365d398006569b28da09b9f33107bd7a8/medal.js#L58


Pulls latest ID checks if its not the same and if it it isn't then it sets the new object
https://github.com/txj-xyz/medal-tv-discord-webhook/blob/54c697e365d398006569b28da09b9f33107bd7a8/medal.js#L68-L69

Full code here:
https://github.com/txj-xyz/medal-tv-discord-webhook/blob/54c697e365d398006569b28da09b9f33107bd7a8/medal.js#L57-L69

**Comment by azpha** [comment] 2022-02-03 17:30
Uploading clips after the script has started will continue to send those specific clips repeatedly, through however many that have been uploaded.

The initial clip that's grabbed when npm start is ran never gets sent again as the checks ensure, but every clip uploaded after the fact gets sent over and over again, alternating between them. Unless this is intended? It could be just me misinterpreting its intended use haha

![image](https://user-images.githubusercontent.com/68027680/152395695-4560019c-2b76-4ffb-a1a3-13a361023d21.png)

**Comment by txj-xyz** [comment] 2022-02-07 19:30
I'll fix this when I have some time on my hands.

I was able to replicate it this weekend, I've decided to recode the entire thing once that happens, I'll have you test again and close this.

**Comment by txj-xyz** [comment] 2022-02-08 21:15
@awexthedev So it appears the issue is related to the Medal API returning different clip IDs for some reason on a `priv_xxxxx` style key, It appears to act at random after awaiting 12 hours straight and uploading throughout the day random clips

It will work then randomly pull a different clip ID, that's why it's looping.

**Comment by azpha** [comment] 2022-02-09 08:51
That would make sense, though I'm not sure why it's randomly timed. that api is weird sometimes lol

**Comment by txj-xyz** [comment] 2022-02-15 14:24
Code works, looks like this is isolated to the API returning different results, try a public key, they seem more consistent?

Closing this.

**Closed as completed by txj-xyz** 2022-02-15 14:24 UTC
Labels: bug
